version: "3.9"

services:
  db:
    image: postgres:16
    container_name: internet_shops_db
    restart: always

    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: islam0203

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: internet_shops_redis
    restart: always

    ports:
      - "6379:6379"

  web:
    build: .

    container_name: internet_shops_web

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn DjangoInternetShops.wsgi:application --bind 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

    environment:
      REDIS_URL: redis://redis:6379/0

  celery:
    build: .

    container_name: internet_shops_celery

    command: celery -A DjangoInternetShops worker -l info

    volumes:
      - .:/app

    depends_on:
      - db
      - redis

    environment:
      REDIS_URL: redis://redis:6379/0

  celery-beat:
    build: .

    container_name: internet_shops_celery_beat

    command: celery -A DjangoInternetShops beat -l info

    volumes:
      - .:/app

    depends_on:
      - db
      - redis

    environment:
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data:
